# Generated by Django 5.2.4 on 2025-07-04 10:08

import django.db.models.deletion
import studentpanel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('duration_weeks', models.PositiveIntegerField(choices=[(4, '4 Weeks'), (6, '6 Weeks')])),
                ('title', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slots', models.PositiveIntegerField()),
                ('slots_taken', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('father_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to=studentpanel.models.photo_upload_path)),
                ('lor_file', models.FileField(upload_to=studentpanel.models.lor_upload_path)),
                ('is_selected', models.BooleanField(default=False)),
                ('payment_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=15)),
                ('selected_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentpanel.project')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentpanel.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pdf', models.FileField(upload_to='idcards/')),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentpanel.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_pdf', models.FileField(blank=True, null=True, upload_to='challans/')),
                ('submitted_copy', models.FileField(blank=True, null=True, upload_to='challans/submitted/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified')], default='Pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentpanel.studentprofile')),
            ],
        ),
    ]
