# Generated by Django 5.2.4 on 2025-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
    ]
