# Generated by Django 5.2.4 on 2025-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='slots_taken',
            field=models.IntegerField(default=0),
        ),
    ]
