# Generated by Django 5.2.4 on 2025-07-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_alter_project_branch_alter_project_project_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration_weeks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='slots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='slots_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
