# Generated by Django 5.2.4 on 2025-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_studentprofile_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feechallan',
            name='submitted_copy',
        ),
        migrations.AddField(
            model_name='feechallan',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feechallan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Submitted', 'Submitted'), ('Verified', 'Verified')], default='Pending', max_length=10),
        ),
    ]
