# Generated by Django 5.2.4 on 2025-07-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0003_alter_project_duration_weeks_alter_project_slots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='teacher',
            new_name='Guide_By',
        ),
    ]
