# Generated by Django 5.2.4 on 2025-07-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0003_remove_feechallan_submitted_copy_feechallan_sent_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentpanel.studentprofile')),
            ],
        ),
    ]
