# Generated by Django 5.2.4 on 2025-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0005_feechallan_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_incharge_name', models.CharField(max_length=100)),
                ('training_incharge_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('director_name', models.CharField(max_length=100)),
                ('director_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
    ]
