# Generated by Django 5.2.4 on 2025-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0006_certificatesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateSettings',
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
