# Generated by Django 5.2.4 on 2025-08-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0007_delete_certificatesettings_certificate_director_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='training_incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
