# Generated by Django 5.2.4 on 2025-08-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0008_feechallan_training_incharge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(default='Director', max_length=200)),
                ('signature', models.ImageField(upload_to='signatures/director/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('signature', models.ImageField(upload_to='signatures/incharge/')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director_signature',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge_signature',
        ),
        migrations.RemoveField(
            model_name='feechallan',
            name='training_incharge_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Guide_By',
        ),
        migrations.AddField(
            model_name='certificate',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.director'),
        ),
        migrations.AddField(
            model_name='feechallan',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.director'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.trainingincharge'),
        ),
        migrations.AddField(
            model_name='feechallan',
            name='training_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.trainingincharge'),
        ),
        migrations.AddField(
            model_name='project',
            name='guide_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
