# Generated by Django 5.2.4 on 2025-08-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0009_director_trainingincharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feechallan',
            name='director',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director',
        ),
        migrations.RemoveField(
            model_name='feechallan',
            name='training_incharge',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge',
        ),
        migrations.RemoveField(
            model_name='project',
            name='guide_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='TrainingIncharge',
        ),
        migrations.AddField(
            model_name='project',
            name='Guide_By',
            field=models.CharField(default='ssc', max_length=100),
            preserve_default=False,
        ),
    ]
