# Generated by Django 5.2.4 on 2025-08-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0010_remove_feechallan_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incharge_name', models.CharField(max_length=100)),
                ('incharge_signature', models.ImageField(blank=True, null=True, upload_to='signatures/incharge/')),
                ('director_name', models.CharField(max_length=100)),
                ('director_signature', models.ImageField(blank=True, null=True, upload_to='signatures/director/')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director_signature',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge_signature',
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.trainingauthority'),
        ),
        migrations.AddField(
            model_name='feechallan',
            name='training_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.trainingauthority'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='training_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentpanel.trainingauthority'),
        ),
    ]
