# Generated by Django 5.2.4 on 2025-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0011_trainingauthority_remove_certificate_director_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingauthority',
            old_name='director_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='trainingauthority',
            name='director_signature',
        ),
        migrations.RemoveField(
            model_name='trainingauthority',
            name='incharge_name',
        ),
        migrations.RemoveField(
            model_name='trainingauthority',
            name='incharge_signature',
        ),
        migrations.AddField(
            model_name='trainingauthority',
            name='role',
            field=models.CharField(choices=[('Incharge', 'Incharge'), ('Director', 'Director')], default='ssc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingauthority',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
