# Generated by Django 5.2.4 on 2025-08-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0012_rename_director_name_trainingauthority_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='training_authority',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_authority',
        ),
        migrations.RemoveField(
            model_name='feechallan',
            name='training_authority',
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.DeleteModel(
            name='TrainingAuthority',
        ),
    ]
