# Generated by Django 5.2.4 on 2025-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0013_remove_idcard_training_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feechallan',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
