# Generated by Django 5.2.4 on 2025-08-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0014_feechallan_director_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signatures/director/')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Director',
            },
        ),
        migrations.CreateModel(
            name='ProjectIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signatures/incharge/')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='director_signature',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training_incharge_signature',
        ),
        migrations.RemoveField(
            model_name='feechallan',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='feechallan',
            name='director_signature',
        ),
    ]
