# Generated by Django 5.2.4 on 2025-08-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0015_director_projectincharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Guide_By',
        ),
        migrations.AddField(
            model_name='project',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studentpanel.projectincharge'),
        ),
    ]
