# Generated by Django 5.2.4 on 2025-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0016_remove_project_guide_by_project_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='concerd_shop',
            field=models.CharField(blank=True, help_text='Enter Concerd Shop name', max_length=100, null=True),
        ),
    ]
