# Generated by Django 5.2.4 on 2025-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0017_project_concerd_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='temp_dummy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_incharge_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='directors/signatures/'),
        ),
    ]
