# Jazzmin Admin Customization
JAZZMIN_SETTINGS = {
    "site_title": "Summer Training Admin",
    "site_header": "Summer Training Portal Admin",
    "site_brand": "Summer Training Portal",
    "copyright": " Design & Developed by <a href='https://www.linkedin.com/in/nilansha-pandey-9586b026b/' target='_blank' style='color:#007bff;font-weight:bold;text-decoration:none;'>Nilansha</a>",
    "welcome_sign": "Welcome to the Summer Training Admin Portal",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["studentpanel", "auth"],
    "custom_links": {},
    "show_ui_builder": False,
    # Side menu icons for each app/model
    "icons": {
        "studentpanel": "fas fa-user-graduate",
        "studentpanel.studentprofile": "fas fa-id-card",
        "studentpanel.feechallan": "fas fa-file-invoice-dollar",
        "studentpanel.project": "fas fa-project-diagram",
        "studentpanel.projectselection": "fas fa-tasks",
        "studentpanel.idcard": "fas fa-address-card",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
    },
    # UI Tweaks
    "theme": "cosmo",  # Try 'cosmo', 'flatly', 'darkly', etc.
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": True,
    "sidebar_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "login_logo": "logo.png",
    "login_logo_dark": "logo.png",
    "site_logo": "logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "logo.png",
    "user_avatar": None,
}
"""
Django settings for summer_training_portal project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$70+(s1dmxxkal6y_ed5!)28v5h9l^(95(#!7r89epjarc@mcx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# settings.py

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
        'jazzmin',
    'studentpanel',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'summer_training_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'summer_training_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Where to send unauthenticated users
LOGIN_URL = "/login/"

# Where to go right *after* a successful login
LOGIN_REDIRECT_URL = "/dashboard/"


# After logging out, send back to login
LOGOUT_REDIRECT_URL = "/admin/login/"


DEFAULT_FROM_EMAIL = "nilansha777@gmail.com"   # अपनी Gmail या SMTP की ID
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "nilansha777@gmail.com"
EMAIL_HOST_PASSWORD = "orezpfrqeqcopknr"
EMAIL_USE_TLS = True
